version: '3'

services:
  app:
    image: openjdk:17
    build:
      context: .
    working_dir: /app
    command: ["java", "-jar", "PollingApp-0.0.1-SNAPSHOT.jar"]
    volumes:
      - ./target:/app
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    networks:
      my-network:
        ipv4_address: 192.168.1.2  # Set your desired IP address for app service

  mariadb:
    container_name: maria
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: pollapp
      MYSQL_USER: ma1581
      MYSQL_PASSWORD: 1581
    ports:
      - "3306:3306"
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
    networks:
      my-network:
        ipv4_address: 192.168.1.3  # Set your desired IP address for mariadb service

networks:
  my-network:
    external: true
    ipam:
      driver: default
      config:
        - subnet: "192.168.1.0/24"
